export const IMAGES = {
  stair1: new URL("./stairs/stair1.webp", import.meta.url).href,
  stair2: new URL("./stairs/stair2.webp", import.meta.url).href,
  stair3: new URL("./stairs/stair3.webp", import.meta.url).href,
  stair4: new URL("./stairs/stair4.webp", import.meta.url).href,
  stair5: new URL("./stairs/stair5.webp", import.meta.url).href,
  stair6: new URL("./stairs/stair6.webp", import.meta.url).href,
  stair7: new URL("./stairs/stair7.webp", import.meta.url).href,
  kitchen1: new URL("./kitchens/kitchen1.webp", import.meta.url).href,
  kitchen2: new URL("./kitchens/kitchen2.webp", import.meta.url).href,
  kitchen3: new URL("./kitchens/kitchen3.webp", import.meta.url).href,
  kitchen4: new URL("./kitchens/kitchen4.webp", import.meta.url).href,
  kitchen5: new URL("./kitchens/kitchen5.webp", import.meta.url).href,
  kitchen6: new URL("./kitchens/kitchen6.webp", import.meta.url).href,
  kitchen7: new URL("./kitchens/kitchen7.webp", import.meta.url).href,
  screen1: new URL("./screens/screen1.webp", import.meta.url).href,
  screen2: new URL("./screens/screen2.webp", import.meta.url).href,
  screen3: new URL("./screens/screen3.webp", import.meta.url).href,
  screen4: new URL("./screens/screen4.webp", import.meta.url).href,
  screen5: new URL("./screens/screen5.webp", import.meta.url).href,
  screen6: new URL("./screens/screen6.webp", import.meta.url).href,
  screen7: new URL("./screens/screen7.webp", import.meta.url).href,
  furniture1: new URL("./furniture/furniture1.webp", import.meta.url).href,
  furniture2: new URL("./furniture/furniture2.webp", import.meta.url).href,
  furniture3: new URL("./furniture/furniture3.webp", import.meta.url).href,
};