export const IMAGES = {
  stair1: new URL("./stairs/stair1.jpg", import.meta.url).href,
  stair2: new URL("./stairs/stair2.jpg", import.meta.url).href,
  stair3: new URL("./stairs/stair3.jpg", import.meta.url).href,
  stair4: new URL("./stairs/stair4.jpg", import.meta.url).href,
  stair5: new URL("./stairs/stair5.jpg", import.meta.url).href,
  stair6: new URL("./stairs/stair6.jpg", import.meta.url).href,
  stair7: new URL("./stairs/stair7.jpg", import.meta.url).href,
  kitchen1: new URL("./kitchens/kitchen1.jpg", import.meta.url).href,
  kitchen2: new URL("./kitchens/kitchen2.jpg", import.meta.url).href,
  kitchen3: new URL("./kitchens/kitchen3.jpg", import.meta.url).href,
  kitchen4: new URL("./kitchens/kitchen4.jpg", import.meta.url).href,
  kitchen5: new URL("./kitchens/kitchen5.jpg", import.meta.url).href,
  kitchen6: new URL("./kitchens/kitchen6.jpg", import.meta.url).href,
  kitchen7: new URL("./kitchens/kitchen7.jpg", import.meta.url).href,
};