export const IMAGES = {
  stair1: new URL("./stairs/stair1.jpg", import.meta.url).href,
  stair2: new URL("./stairs/stair2.jpg", import.meta.url).href,
  stair3: new URL("./stairs/stair3.jpg", import.meta.url).href,
  stair4: new URL("./stairs/stair4.jpg", import.meta.url).href,
  stair5: new URL("./stairs/stair5.jpg", import.meta.url).href,
  stair6: new URL("./stairs/stair6.jpg", import.meta.url).href,
  stair7: new URL("./stairs/stair7.jpg", import.meta.url).href,
  kitchen1: new URL("./kitchens/kitchen1.jpg", import.meta.url).href,
  kitchen2: new URL("./kitchens/kitchen2.jpg", import.meta.url).href,
  kitchen3: new URL("./kitchens/kitchen3.jpg", import.meta.url).href,
  kitchen4: new URL("./kitchens/kitchen4.jpg", import.meta.url).href,
  kitchen5: new URL("./kitchens/kitchen5.jpg", import.meta.url).href,
  kitchen6: new URL("./kitchens/kitchen6.jpg", import.meta.url).href,
  kitchen7: new URL("./kitchens/kitchen7.jpg", import.meta.url).href,
  screen1: new URL("./screens/screen1.jpg", import.meta.url).href,
  screen2: new URL("./screens/screen2.jpg", import.meta.url).href,
  screen3: new URL("./screens/screen3.jpg", import.meta.url).href,
  screen4: new URL("./screens/screen4.jpg", import.meta.url).href,
  screen5: new URL("./screens/screen5.jpg", import.meta.url).href,
  screen6: new URL("./screens/screen6.jpg", import.meta.url).href,
  screen7: new URL("./screens/screen7.jpg", import.meta.url).href,
  furniture1: new URL("./furniture/furniture1.jpg", import.meta.url).href,
  furniture2: new URL("./furniture/furniture2.jpg", import.meta.url).href,
  furniture3: new URL("./furniture/furniture3.jpg", import.meta.url).href,
};